{% set name = "esparto" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esparto-{{ version }}.tar.gz
  sha256: 6777e6b4bc29952f8752d686343d01dcaa789016a8ed422325827e3d89562acc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - dataclasses
    - jinja2 >=2.10.1,<4.0.0
    - markdown >=3.1,<4.0
    - pillow >=7.0.0,<9
    - python >=3.6
    - pyyaml >=5.1

test:
  imports:
    - esparto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://domvwt.github.io/esparto
  summary: Simple HTML page and PDF document generator for Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://domvwt.github.io/esparto/
  dev_url: https://github.com/domvwt/esparto

extra:
  recipe-maintainers:
    - domvwt
