{% set name = "esparto" %}
{% set version = "4.0.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esparto-{{ version }}.tar.gz
  sha256: b4c55291734e3b620268a0ffc104dba04b93f06d8cd610136c21fec401fc59ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - beautifulsoup4 >=4.7
    - dataclasses
    - jinja2 >=2.10.1
    - markdown >=3.1
    - python >=3.6
    - pyyaml >=5.1

test:
  imports:
    - esparto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://domvwt.github.io/esparto
  summary: Data driven report builder for the PyData ecosystem.
  license: MIT
  license_file: LICENSE
  doc_url: https://domvwt.github.io/esparto/
  dev_url: https://github.com/domvwt/esparto

extra:
  recipe-maintainers:
    - domvwt
